#!/bin/bash

#---------------------------------------------------------------------------------
#	Architecture file for compiling and running CHIMERE	
#	Specify path to libraries, compilers and utilities 
#---------------------------------------------------------------------------------


#---------------------------------------------------------------------------------
# 	Compilers
#---------------------------------------------------------------------------------
export my_compilerF90=/usr/bin/gfortran		# Path to Fortran 90 compiler
export my_compilerC=/usr/bin/gcc				  # Path to C compiler
export my_compilerCpp=/usr/bin/g++				# Path to C++ compiler


#---------------------------------------------------------------------------------
# 	MPI - parallel execution of chimere
#---------------------------------------------------------------------------------
export  my_mpiframe=openmpi  			                              # implementation of MPI norm [ ompi / ccrt ] TO REMOVE
export  my_mpibin=/chim/libs/openmpi/BUILD_DIR/bin    			    # Path to MPI binary directory
export  my_mpirun=/chim/libs/openmpi/BUILD_DIR/bin/mpirun    	  # Path to mpirun to execute parallel job in MPI
export  my_mpif90=/chim/libs/openmpi/BUILD_DIR/bin/mpif90    		# Wrapper to my_compilerF90 to link with MPI library
export  my_mpicc=/chim/libs/openmpi/BUILD_DIR/bin/mpicc         # Wrapper to my_compilerC to link with MPI library
export  my_mpilib=/chim/libs/openmpi/BUILD_DIR/lib/openmpi    	# Path to MPI libraries directory
export  my_mpiinc=/chim/libs/openmpi/BUILD_DIR/include/openmpi  # Path to MPI include files directory


#---------------------------------------------------------------------------------
# 	HDF5  - parallel version	
#---------------------------------------------------------------------------------
export my_hdflib=/chim/libs/hdf5/BUILD_DIR/lib		    # Path to HDF5 parallel library directory
export my_hdfinc=/chim/libs/hdf5/BUILD_DIR/include		# Path to HDF5 parallel include files directory


#---------------------------------------------------------------------------------
# 	NETCDF-C  - link with HDF5 parallel 
#---------------------------------------------------------------------------------
export my_netcdfCbin=/chim/libs/netcdf/bin/ 		# Path to NETCDF-C (linked with HDF5 parallel) binaries directory
export my_netcdfClib=/chim/libs/netcdf/lib/		# Path to NETCDF-C (linked with HDF5 parallel) library directory


#---------------------------------------------------------------------------------
# 	NETCDF-Fortran  - link with HDF5 parallel and NETCDF-C
#---------------------------------------------------------------------------------
export my_netcdfF90bin=/chim/libs/netcdf/bin/        # PATH to NETCDF-Fortran (linked with HDF5 parallel and NETCDF-C) binaries  directory
export my_netcdfF90lib=/chim/libs/netcdf/lib/ 		    # Path to NETCDF-Fortran (linked with HDF5 parallel and NETCDF-C) library  directory
export my_netcdfF90inc=/chim/libs/netcdf/include/ 		# Path to NETCDF-Fortran (linked with HDF5 parallel and NETCDF-C) include files  directory


#---------------------------------------------------------------------------------
# 	GRIB  - link with jasper 
#---------------------------------------------------------------------------------
export my_griblib=/chim/libs/eccodes/BUILD_DIR/lib64     	# Path to GRIB library directory
export my_gribinc=/chim/libs/eccodes/BUILD_DIR/include 		# Path to GRIB include files directory
export my_jasperlib=/chim/libs/jasper/BUILD_DIR/lib  			# Path to JASPER library directory
export my_jasperinc=/chim/libs/jasper/BUILD_DIR/include		# Path to JASPER include files directory


#---------------------------------------------------------------------------------
# 	BLITZ
#---------------------------------------------------------------------------------
export my_blitzinc=/chim/libs/blitz/BUILD_DIR/include		 # Path to BLITZ include files


#---------------------------------------------------------------------------------
# 	Utilities	
#---------------------------------------------------------------------------------
export my_make=make 		                # Path to make
export my_awk=awk			                  # Path to awk
export my_ncdump=/chim/libs/netcdf/bin		# Path to ncdump


#---------------------------------------------------------------------------------
# 	Makefile header needed to compile CHIMERE and WRF 
#	     - with this architecture configuration - 	
#---------------------------------------------------------------------------------
export my_hdr=Makefile.hdr.gfortran-64-ompi             # Makefile header to compile CHIMERE in makefiles.hdr directory
export configure_wrf_file_name=configure.wrf.gfortran   # Makefile header to compile WRF in config_wrf directory
export configure_wps_file_name=configure_gfortran.wps  	# Makefile header to compile WPS in config_wps directory


#---------------------------------------------------------------------------------
#	Export of Shared Library to be available at run time 	
#---------------------------------------------------------------------------------
export LD_LIBRARY_PATH=${my_hdflib}:${my_netcdfF90lib}:${my_netcdfClib}:${my_griblib}:${my_mpilib}:${my_mpilib}/openmpi:$LD_LIBRARY_PATH




