name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - uses: actions/checkout@v3
      - name: Build the Docker image
        uses: docker/build-push-action@v3
        with:
          tags: chimere_conae
          file: Dockerfile_test
          secrets: |
            "secret_user=${{ secrets.CHIMERE_USER }}"
            "secret_pass=${{ secrets.CHIMERE_PASS }}"
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      #run: DOCKER_BUILDKIT=1 docker build . --file Dockerfile --tag chimere_conae:$(date +%FT%H_%M_%S)
