name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - uses: actions/checkout@v3
      - name: Build the Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: user/app:latest
          file: Dockerfile
          secrets: |
            "secret_user=${{ secrets.CHIMERE_USER }}"
            "secret_pass=${{ secrets.CHIMERE_PASS }}"
      #run: DOCKER_BUILDKIT=1 docker build . --file Dockerfile --tag chimere_conae:$(date +%FT%H_%M_%S)
